### PR TITLE
add context properties to requestStart type

### PR DESCRIPTION
**Pull request by koenpunt**
Matching https://github.com/apollographql/apollo-server/blob/c4e81206e841fbd670fa375010fe3c68372350a3/packages/graphql-extensions/src/index.ts#L40-L41

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
I'm sorry @koenpunt this fell through the cracks. The change looks great, do you have time to rebase it, so we can get this merged?

**Comment by koenpunt** [comment]
Done!

**Comment by koenpunt** [comment]
Ping ✨

**Comment by DanielMSchmidt** [comment]
Thanks for pinging me again 👍

**Pull request merged**
