### PR TITLE
add onRequestError callback

### PR DESCRIPTION
**Pull request by leeweisberger**
Add callback when the request errors along with the root span

### CODE REVIEW

**Review by StarpTech — APPROVED** [review]
Great PR, LGTM

**Comment by StarpTech** [comment]
Friendly ping @DanielMSchmidt

**Review by DanielMSchmidt — APPROVED** [review]

**Comment by DanielMSchmidt** [comment]
Sorry for the delay folks!

**Comment by DanielMSchmidt** [comment]
I fixed CI, could you rebase @leeweisberger?

**Comment by StarpTech** [comment]
This will fix #438

**Comment by StarpTech** [comment]
@DanielMSchmidt when can we expect a release?

**Comment by DanielMSchmidt** [comment]
Ah snap, I forgot to check the commits. Normally everything is automatically released after merge, but in this case the commit message was not following the conventional commit schema. I'll do an empty commit with a message that triggers a release

**Comment by StarpTech** [comment]
@DanielMSchmidt thank you!

**Pull request merged**
