### PR TITLE
fix(headers): extract headers parameter

### PR DESCRIPTION
**Pull request by voslartomas**
Apollo is converting request object to map, but open tracing interface (specifically jaeger client) expects object in extract method, therefore converting headers (only if it's type of map) to object.

### CODE REVIEW

**Comment by voslartomas** [comment]
@DanielMSchmidt using apollo-server@2.4.2

**Comment by DanielMSchmidt** [comment]
Thank you for your help @voslartomas, could you change the peerDependency to be >= 2.4.2 for apollo-server as well?

**Comment by voslartomas** [comment]
@DanielMSchmidt You mean to in our repo, to test if it works? Or in this PR?

**Comment by DanielMSchmidt** [comment]
@voslartomas In this PR

**Comment by mwieczorek** [comment]
@voslartomas will you continue on this PR? (just asking as I'm also hitting this issue)

**Comment by voslartomas** [comment]
@mwieczorek Well I am done with this, fixed issue and updated things @DanielMSchmidt suggested. So waiting for review. For now I am using my fork.

**Comment by mwieczorek** [comment]
oh, ok, I saw the conflict and 'commitlint' errors so I thought it needs some more work. If not let's wait for @DanielMSchmidt

**Comment by DanielMSchmidt** [comment]
Sorry about being so inactive here, I think the code is fine. The only thing missing as @mwieczorek pointed out would be the commit format that we follow. This is important because if we merge it like this semantic-release won't cut a release with your changes. If you'd squash them into a `fix: extract header parameters` commit I can go ahead and merge the PR 👍

**Comment by voslartomas** [comment]
Github supports squash merge by itself, do you think you could do that via github? Because right now after pull it's a mess in history, not sure how elegantly squash only my changes.

**Pull request merged**
